spring:
  application:
    name: user-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}